### ISSUE TITLE
求助，部署在fly.io上，数据无法保存，重启项目订阅源就都没了

### ISSUE THREAD

**Issue by waltergas** [fengkx/NodeRSSBot#1070]
heroku收费了，于是想找个替代的，找到了fly.io。

fly.io能通过docker部署本项目，telegram bot也能正常运行，但是有两个问题：
（1）重启或者更新部署，数据就丢失了，之前的订阅源都没了。部署的时候，分配了1个G的硬盘空间，项目也能在指定位置创建database，但只要项目重启或者更新，数据就没了。
（2）通过fly.io定义的Secret Variables环境变量无法生效

大佬有空的话，帮忙看看。谢谢

**Comment by fengkx** [comment]
https://fly.io/docs/reference/volumes/
