### ISSUE TITLE
Local config files for different channels / feeds

### ISSUE THREAD

**Issue by cmp0xff** [fengkx/NodeRSSBot#130]
It seems to me that the config file is global, and one cannot use, for example, different `fetch_gap`, for different channels / feeds, which might be desirable.

**Comment by fengkx** [comment]
For now, the feed is fetched by another process in a certain gap. I would like to stay it globally. Because if we need to set different feed a different gap, the complexity will increase largely. Especially when there are multi-user subscribe to the same feed which is a common case.

**Comment by cmp0xff** [comment]
感謝迅速回覆。
