### ISSUE TITLE
新加订阅出错

### ISSUE THREAD

**Issue by xinxijishuwyq** [fengkx/NodeRSSBot#135]
如图，新添加订阅一直显示正在处理中请稍后。发送其他指令无响应。重启机器人依旧会出现“正在处理中请稍后”
![image](https://user-images.githubusercontent.com/1755898/76140476-c46b9580-6095-11ea-897a-2920e124103b.png)

**Comment by xinxijishuwyq** [comment]
这个问题似乎是在nodejs13的某个版本后才出现的，我换成nodejs12后解决了

**Comment by fengkx** [comment]
issue先不急着关。能提供具体的node版本号和log吗？你是怎么启动bot的。

**Comment by xinxijishuwyq** [comment]
> issue先不急着关。能提供具体的node版本号和log吗？你是怎么启动bot的。

node是13.10.1，启动方式是按照你写的，第一次“pm2 start npm --name node_rssbot -- start”，往后pm2 start node_rssbot

日志的话刚才我删了，我在本地复现一下

**Comment by xinxijishuwyq** [comment]
不好意思，“一直显示正在处理中请稍后”这个问题没有成功复现。
但是rss抓取似乎没有正常工作
我刚才尝试订阅了“https://lorem-rss.herokuapp.com/feed?unit=second”，每秒钟都更新的rss
而程序我设置的更新频率是1分钟，几分钟过去了都没接到消息
![image](https://user-images.githubusercontent.com/1755898/76143698-947fba80-60b4-11ea-928f-2c471447bd27.png)
![image](https://user-images.githubusercontent.com/1755898/76143703-977aab00-60b4-11ea-9249-11f2b2114a8b.png)

**Comment by xinxijishuwyq** [comment]
> 不好意思，“一直显示正在处理中请稍后”这个问题没有成功复现。
> 但是rss抓取似乎没有正常工作
> 我刚才尝试订阅了“[https://lorem-rss.herokuapp.com/feed?unit=second”，每秒钟都更新的rss](https://lorem-rss.herokuapp.com/feed?unit=second%E2%80%9D%EF%BC%8C%E6%AF%8F%E7%A7%92%E9%92%9F%E9%83%BD%E6%9B%B4%E6%96%B0%E7%9A%84rss)
> 而程序我设置的更新频率是1分钟，几分钟过去了都没接到消息
> ![image](https://user-images.githubusercontent.com/1755898/76143698-947fba80-60b4-11ea-928f-2c471447bd27.png)
> ![image](https://user-images.githubusercontent.com/1755898/76143703-977aab00-60b4-11ea-9249-11f2b2114a8b.png)

{"message":"Database file is in /home/ken/NodeRSSBot/data/database.db","level":"info","timestamp":"2020-03-07T12:40:16.826Z"}
{"message":"Using Default language is zh-cn","level":"info","timestamp":"2020-03-07T12:40:16.831Z"}
{"message":"send the latest 10 items for each feed","level":"info","timestamp":"2020-03-07T12:40:16.832Z"}
{"message":"NodeRSSBot is ready","level":"info","timestamp":"2020-03-07T12:40:16.833Z"}
{"message":"init tables in /home/ken/NodeRSSBot/data/database.db","level":"info","timestamp":"2020-03-07T12:40:16.836Z"}
{"message":"start fetching","level":"info","timestamp":"2020-03-07T12:40:17.350Z"}
{"message":"fetch every 1 minutes","level":"info","timestamp":"2020-03-07T12:40:17.351Z"}
{"message":"start fetching","level":"info","timestamp":"2020-03-07T12:41:00.039Z"}
{"message":"start fetching","level":"info","timestamp":"2020-03-07T12:42:00.062Z"}
{"message":"start fetching","level":"info","timestamp":"2020-03-07T12:43:00.064Z"}
{"message":"start fetching","level":"info","timestamp":"2020-03-07T12:44:00.062Z"}

**Comment by fengkx** [comment]
我成功在`node v13.10.1`复现了这个问题。发现是因为程序卡在了HTTP请求`got`中。
参考 https://github.com/sindresorhus/got/issues/1107

暂时先回退到`13.10` 以下的版本吧

**Comment by xinxijishuwyq** [comment]
nodejs 13.11.0下已经正常。
谢谢。

**Comment by fengkx** [comment]
添加相关测试。以避免类似情况出现
https://github.com/fengkx/NodeRSSBot/commit/1cb7ea61db8756453b8670a529582f224deb733a
