### ISSUE TITLE
退订提示 找不到该 id 对应频道

### ISSUE THREAD

**Issue by NeverBehave** [fengkx/NodeRSSBot#140]
![截屏2020-03-19下午8 19 58](https://user-images.githubusercontent.com/17120571/77126371-3a211b00-6a1f-11ea-9bdc-c36d54f215e1.png)
![截屏2020-03-19下午8 20 18](https://user-images.githubusercontent.com/17120571/77126373-3beade80-6a1f-11ea-8992-07b96f9507a5.png)
![截屏2020-03-19下午8 19 49](https://user-images.githubusercontent.com/17120571/77126374-3c837500-6a1f-11ea-8be6-8c79e3cf19df.png)

订阅链接：https://rsshub.app/kuaidi100/track/upsen/1ZR721V23932735859

**Comment by fengkx** [comment]
7cabb1ee45f954604652ffb6fc741eabe79bf0ae 更新到最新master再试试看。

**Comment by NeverBehave** [comment]
唔，这样子看来还是有可能会与title有冲突

但是目前而言问题应该解决了
