### ISSUE TITLE
Repeated messages for new posts

### ISSUE THREAD

**Issue by luk1337** [fengkx/NodeRSSBot#1537]
**Demo or Self hosted**

-   [x] Demo
-   [ ] Self hosted

**Describe the bug**
I'm getting duplicate messages for new posts.

**To Reproduce**
Subscribe to new feed and wait.

**Expected behavior**
No duplicate messages.

**Screenshots / Logs**
![Screenshot_20240120-231124](https://github.com/fengkx/NodeRSSBot/assets/6830979/eb42a54f-960b-4b4c-99b6-a35e4527d394)

**Comment by fengkx** [comment]
investigating...

**Comment by luk1337** [comment]
Seems like this is no longer an issue.
