### ISSUE TITLE
无法正常订阅某一个rss源，报错代码：429

### ISSUE THREAD

**Issue by April-BOY** [fengkx/NodeRSSBot#1765]
订阅源：https://rsshub.app/ithome/tag/5g
描述：其他订阅源正常，唯独这个订阅源不能正常订阅。订阅源本身是可以正常访问的。
报错信息：IT之家 - 5g标签: https://rsshub.app/ithome/tag/5g 多次抓取失败，建议取消订阅 Request failed with status code 429 Too Many Requests

**Comment by fengkx** [comment]
Demo triggered RSSHub rate limit. You can host your own instance.
