### ISSUE TITLE
Dockerfile for Raspberry Pi

### ISSUE THREAD

**Issue by DrNion** [fengkx/NodeRSSBot#191]
Hey it's me again,

I haven't done an update since v0.3.1 and I'd like to update.
Since you wrote me last time to use a different Dockerfile which worked back then I'd like you to ask you what Dockerfile I should use for v0.6.1

My Dockerfile from v0.3.1 was:
```
FROM arm32v7/node:12.12-alpine`
WORKDIR /app`
RUN apk add --no-cache --update build-base python2`
COPY . /app`
ENV NODE_PRODUTION true
RUN npm install --production 
ENTRYPOINT npm run start
```
It seems that it doesn't work after updating to v0.6.1, I also tried it with `FROM arm32v7/node:current-alpine`.

Another Dockerfile I tried was that one:
```
FROM arm32v7/node:current-alpine as ts-builder
WORKDIR /app
COPY . /app
RUN npm install --ignore-scripts && npm run build

FROM arm32v7/node:current-alpine as dep-builder
WORKDIR /app
COPY package.json clean-nm.sh /app/
RUN apk add --no-cache --update build-base python2
RUN npm install --production && sh /app/clean-nm.sh

FROM arm32v7/node:current-alpine as app
WORKDIR /app
ENV NODE_PRODUTION true
COPY data /app/data
COPY logs /app/logs
COPY package.json /app/package.json
COPY --from=ts-builder /app/dist /app/dist
COPY --from=dep-builder /app/node_modules /app/node_modules
CMD npm run start-withsnapshot
```
Without any success...

My system didn't change, I'm still using raspbian stretch.

Thanks :)

**Comment by fengkx** [comment]
The problem maybe because I switched to better-sqlite3. Maybe you should try setting environment variable mentioned in this issue first https://github.com/JoshuaWise/better-sqlite3/issues/41

```dockerfile
FROM arm32v7/node:current-alpine as ts-builder
WORKDIR /app
COPY . /app
RUN npm install --ignore-scripts && npm run build

FROM arm32v7/node:current-alpine as dep-builder
WORKDIR /app
COPY package.json clean-nm.sh /app/
RUN apk add --no-cache --update build-base python2
RUN LZZ_COMPAT=1 npm install --production && sh /app/clean-nm.sh

FROM arm32v7/node:current-alpine as app
WORKDIR /app
ENV NODE_PRODUTION true
COPY data /app/data
COPY logs /app/logs
COPY package.json /app/package.json
COPY --from=ts-builder /app/dist /app/dist
COPY --from=dep-builder /app/node_modules /app/node_modules
CMD npm run start-withsnapshot
```

Please provide the build log or runtime log. I cannot figure out the issue from a simple `without any success`

**Comment by DrNion** [comment]
All right, I will try it when I have time with `LZZ_COMPAT=1` and tell you the logs if it doesn't work.

**Comment by fengkx** [comment]
@DrNion Is setting the environment variable fix the problem?

**Comment by DrNion** [comment]
Everything works now, I think [LZZ_COMPAT=1](https://github.com/JoshuaWise/better-sqlite3/issues/41) did the trick.

I used the same environment variables like last time:
```
docker run --platform=linux/armv71 --name rssbot --restart unless-stopped -d -v /home/pi/telepot/NodeRSSBot/data:/app/data/ -e RSSBOT_TOKEN=<<bot-token>> -e RSSBOT_LANG=en -e RSSBOT_VIEW_ALL=true <<image-ID>>
```
Sorry that I took so long to answer but I had no access to my RPi for the last couple of days.

Thanks again for your help! :)
