### ISSUE TITLE
Change feed output format

### ISSUE THREAD

**Issue by hrvstr** [fengkx/NodeRSSBot#202]
Is it possible to change the output format for the RSS feeds? At the moment it always combines 10 feed items into one message. I would like to get an individual message for each item and maybe display the body text too instead of only showing the headline as a link.

Thanks for the amazing bot btw!

**Comment by fengkx** [comment]
For now, It is not possible.

> it always combines 10 feed items into one message

In fact, It is not always 10 feed items. It depends on the number of updated item from last fetch. You can set the `item_num` or `RSSBOT_ITEM_NUM` environment variable to change the default value 10 according to the [document](https://github.com/fengkx/NodeRSSBot/wiki/English-Document).




>  get an individual message for each item

I think it will become annoying if there is too many new item. But maybe I can make a configuration about it.

> display the body text

I thought about this before. But the body is too large to fit in a message.

**Comment by hrvstr** [comment]
Sorry for the late reply. I see how it would be annoying for some use cases.
For now I settled for "AximoBot" which I don't have to host myself and it also does Instagram and YouTube posts. I will keep an eye on this project though. 👀
