### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by ifwangs** [fengkx/NodeRSSBot#21]
npm start

> noderssbot@0.0.1 start /root/NodeRSSBot
> node index

/root/NodeRSSBot/index.js:24
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Linux 4.20.0-1.el7.elrepo.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! noderssbot@0.0.1 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noderssbot@0.0.1 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the noderssbot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs noderssbot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls noderssbot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/NodeRSSBot/npm-debug.log

**Comment by fengkx** [comment]
请升级node 版本太低了
