### ISSUE TITLE
Single User Mode

### ISSUE THREAD

**Issue by Syusyuly** [fengkx/NodeRSSBot#250]
Could you please offer a switch to enable single user mode when providing Telegram User ID? My Telegram Bot is only geared to the needs for myself. [The Rust version Telegram RSSBOT](https://github.com/iovxw/rssbot) has archieved this awesome feature, I hope you wil follow it up. Thanks!

**Comment by fengkx** [comment]
Added a [allow list configuration](https://github.com/fengkx/NodeRSSBot/wiki/English-Document#setting) for this. You can give it a try now
