### ISSUE TITLE
[Feature]支持heroku部署

### ISSUE THREAD

**Issue by walterjobs** [fengkx/NodeRSSBot#256]
为什么在heroku部署，一会好一会又不能用了？应该不是半小时休眠问题，一般用个几分钟就坏了

**Comment by walterjobs** [comment]
error R10 Web process failed to bind to $PORT within 60 seconds of launch

**Comment by fengkx** [comment]
用[worker dynos](https://devcenter.heroku.com/articles/background-jobs-queueing) 但是heroku的文件系统不是持久的，所以每次重启都会丢掉所有数据。

**Comment by walterjobs** [comment]
> 用[worker dynos](https://devcenter.heroku.com/articles/background-jobs-queueing) 但是heroku的文件系统不是持久的，所以每次重启都会丢掉所有数据。

谢谢大佬的回答。。确实过段时间，数据就都没了。。。还想请问能够部署在vercel上么？谢谢

**Comment by fengkx** [comment]
不能部署在vercel，#257 增加了其他数据库的支持。PostgreSQL 我稍微测试过了，应该没啥问题。你可以先行使用这个分支。Heroku 有 [PostgreSQL 的服务](https://devcenter.heroku.com/articles/heroku-postgresql)，也是有免费额度的，并且数据是持久的非常适合自建。

**Comment by walterjobs** [comment]
> 不能部署在vercel，#257 增加了其他数据库的支持。PostgreSQL 我稍微测试过了，应该没啥问题。你可以先行使用这个分支。Heroku 有 [PostgreSQL 的服务](https://devcenter.heroku.com/articles/heroku-postgresql)，也是有免费额度的，并且数据是持久的非常适合自建。

好的，谢谢您的耐心回复。我周末研究下，多谢

**Comment by fengkx** [comment]
@walterjobs https://rssbot.vercel.app/zh/deploy/heroku

**Comment by walterjobs** [comment]
> @walterjobs https://rssbot.vercel.app/zh/deploy/heroku

谢谢，感谢一键部署。已成功，蟹蟹

**Comment by walterjobs** [comment]
> @walterjobs https://rssbot.vercel.app/zh/deploy/heroku

为什么推送一切正，但是/sub /help等所有命令过了一会就会没反应，需要重启才可以。
