### ISSUE TITLE
请教一个小问题

### ISSUE THREAD

**Issue by skylershu** [fengkx/NodeRSSBot#259]
首先感谢做出这样的 Telegram Bot，请问一键部署到 Heroku 的 bot 这里能不能修改（见图）？新手第一次部署到 Heroku，想要自定义一些信息在 bot 的开始页。

<img width="539" alt="1" src="https://user-images.githubusercontent.com/51185496/98537392-28e59100-22c4-11eb-9fa6-e987b4947042.png">

**Comment by fengkx** [comment]
现在不能，你想改啥

**Comment by skylershu** [comment]
> 现在不能，你想改啥

感谢回复，我想在图片中框选的地方添加一些自定义信息。

**Comment by fengkx** [comment]
具体一点

**Comment by skylershu** [comment]
> 具体一点

某个人第一次使用 bot 开始 /start，bot 回复的命令中可以添加或修改一些自定义内容。比如将图片中的回复内容改得更为精简一点：

> 使用方法：
> /rss - 显示订阅列表，加 `raw`显示链接
> /sub - 订阅 RSS: /sub http://example.com/feed.xml
> /unsub - 退订 RSS: /unsub http://example.com/feed.xml
> /import - 导入 OPML
> /export - 导出为 OPML
> /unsubthis - 回复一个 RSS 发来的消息退订该 RSS
> /allunsub - 退订所有源
> /viewall - 查看所有订阅和订阅人数 需要在设置中打开
> /lang - 更改语言
> /heath - 展示活跃订阅源的健康程度

请问这可以做到吗？

**Comment by fengkx** [comment]
这实际上就是少了第一行。并没有什么不同。你可以自行修改start command中的代码

**Comment by skylershu** [comment]
> 这实际上就是少了第一行。并没有什么不同。你可以自行修改start command中的代码

好的，感谢耐心回复。
