### ISSUE TITLE
多个订阅源报错

### ISSUE THREAD

**Issue by 9Panda3** [fengkx/NodeRSSBot#269]
NodeRSSBot, [04.12.20 03:30]
站酷 - 设计师爱动效: https://rsshub.app/zcool/user/14959636 多次抓取失败，建议取消订阅 Response code 404 (Not Found)

NodeRSSBot, [04.12.20 04:30]
站酷 - 腾讯ISUX: https://rsshub.app/zcool/user/1936779 多次抓取失败，建议取消订阅 Response code 404 (Not Found)

用inoreader能看得到内容。

**Comment by fengkx** [comment]
一直持续这样吗？

**Comment by 9Panda3** [comment]
是的，持续发生，每天都有新的报错

发自我的iPhone

**Comment by 9Panda3** [comment]
> 一直持续这样吗？ 自建还是Demo?

用的tg的bot

**Comment by fengkx** [comment]
我订阅了上面的链接。几天都没有报错。

**Comment by 9Panda3** [comment]
![image](https://user-images.githubusercontent.com/61393145/101334626-148cb800-38b3-11eb-9331-9b717dee5874.png)
NodeRSSBot, [06.12.20 15:17]
站酷 - Alan海七: http://rsshub.app/zcool/user/alan287 多次抓取失败，建议取消订阅 Response code 404 (Not Found)

NodeRSSBot, [07.12.20 00:30]
站酷 - HOWAIKIT牛牛: https://rsshub.app/zcool/user/19221647 多次抓取失败，建议取消订阅 Response code 404 (Not Found)

我这每天都有新的...

**Comment by fengkx** [comment]
所以你到底用的哪个bot。我这一个站酷404的log都没有
![image](https://user-images.githubusercontent.com/16515468/101340847-3d18b000-38bb-11eb-9b79-d969c17756af.png)

**Comment by 9Panda3** [comment]
![image](https://user-images.githubusercontent.com/61393145/101346935-478b7780-38c4-11eb-931a-9c8fcb6db7ab.png)

**Comment by fengkx** [comment]
现在db里的error_count 已经重置（抓取成功时会置零)而且没有log。无法复现问题。得在观察几天

![image](https://user-images.githubusercontent.com/16515468/101367209-e1611d80-38e0-11eb-9eaf-43bf63611f3d.png)

**Comment by fengkx** [comment]
![image](https://user-images.githubusercontent.com/16515468/101854871-5bbdc600-3b9d-11eb-9935-7ac710833f9b.png)
几天过去了，这几个zcool的源都没有出错。考虑到出错的源都是zcool,应该是网络波动。如追求稳定性建议自建。
