### ISSUE TITLE
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by insoxin** [fengkx/NodeRSSBot#304]
指令消息没有回复查看日志

Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

但是过阵子又会自动恢复

间断性反复出现这个

https://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of

答案在这里

**Comment by fengkx** [comment]
Bot 没有 web process 直接关掉就行。
