### ISSUE TITLE
建议 - 可以添加网页预览吗？

### ISSUE THREAD

**Issue by TigerCubDen** [fengkx/NodeRSSBot#458]
![image](https://user-images.githubusercontent.com/55782476/124378884-78128300-dce6-11eb-87e9-c97822353613.png)

如图所示。在推送消息时，不仅仅提供新增文章的标题，同时提供网页预览（page preview）。
这样，很多文章不用跳转到浏览器也能一窥究竟了。
Telegram Bot API 提供了相关参数，只需打开就可以了。

**Comment by fengkx** [comment]
当初开发这个Bot就是想要可以调整抓取间隔不要那么频繁的刷屏。在一个长的时间间隔内同一个subscription的多条消息能合并发送。但是Telegraph Instant View不能。 所以暂时不考虑。

_Originally posted by @fengkx in https://github.com/fengkx/NodeRSSBot/issues/64#issuecomment-537000549_

当一条消息有多个链接时，打开preview不太合理。

**Comment by TigerCubDen** [comment]
好吧
