### ISSUE TITLE
rssbot 更新提醒重复

### ISSUE THREAD

**Issue by walterjobs** [fengkx/NodeRSSBot#474]
作者大大，您好。一直用您的bot来提醒rss更新。
但是有时候会出bug：RSS会重复提醒内容。一般复现在删除内容的时候，会推送删除的项目之前的内容。
不知道是不是订阅源新旧内容的比较算法的问题，只要有不同就会推送更新，但其实是因为订阅源中删除了内容，导致了旧的内容会重复推送了。
希望您能抽空看看，谢谢

**Comment by fengkx** [comment]
自建还是demo，自建的话有没有更新至最新master分支。请按照template 提issue

**Comment by walterjobs** [comment]
> 自建还是demo，自建的话有没有更新至最新master分支。请按照template 提issue

自建的，更新最新的了。好的

**Comment by fengkx** [comment]
好了那就关了，最新的应该是没问题的
