### ISSUE TITLE
rss不正常更新

### ISSUE THREAD

**Issue by xinxijishuwyq** [fengkx/NodeRSSBot#49]
今天git pull之后发现无法正常收到rss更新，多次回滚到
https://github.com/fengkx/NodeRSSBot/commit/748e6b45cc550660a82029ef35f807c9a7704e85
才正常--
系统archlinux，node版本v11.15.0

**Comment by fengkx** [comment]
能否提供一下日志信息？ BTW有没有重新安装依赖？

**Comment by xinxijishuwyq** [comment]
> 能否提供一下日志信息？ BTW有没有重新安装依赖？
刚才通过

rm -rf node_modules
rm package-lock.json
npm cache clear --force
npm install
尝试了，问题依旧

**Comment by xinxijishuwyq** [comment]
> 能否提供一下日志信息？ BTW有没有重新安装依赖？

 NodeRSSBot git:(master) ✗ node index.js
info: Database file is in /home/ken/NodeRSSBot/data/database.db {"timestamp":"2019-06-20T12:14:44.684Z"}
info: Using language is zh-cn {"timestamp":"2019-06-20T12:14:44.694Z"}
info: send the latest 10 items for each feed {"timestamp":"2019-06-20T12:14:44.695Z"}
info: NodeRSSBot is ready {"timestamp":"2019-06-20T12:14:44.695Z"}
Debugger listening on ws://127.0.0.1:46209/cfe6a7db-81e0-4915-aff6-f999d1e4859c
For help, see: https://nodejs.org/en/docs/inspector
info: init tables in /home/ken/NodeRSSBot/data/database.db {"timestamp":"2019-06-20T12:14:44.754Z"}

**Comment by xinxijishuwyq** [comment]
我在本地又尝试了下，依旧有问题，但是如果打开调试再关掉就会好起来。。。
  ~/NodeRSSBot   master ●  node index.js
info: Database file is in /home/ken/NodeRSSBot/data/database.db {"timestamp":"2019-06-20T12:42:16.605Z"}
info: Using language is zh-cn {"timestamp":"2019-06-20T12:42:16.607Z"}
info: send the latest 10 items for each feed {"timestamp":"2019-06-20T12:42:16.608Z"}
info: NodeRSSBot is ready {"timestamp":"2019-06-20T12:42:16.608Z"}
Debugger listening on ws://127.0.0.1:46209/0900d6b7-c816-47b3-9086-0d5d5e79bf0b
For help, see: https://nodejs.org/en/docs/inspector
info: init tables in /home/ken/NodeRSSBot/data/database.db {"timestamp":"2019-06-20T12:42:16.630Z"}
Debugger attached.
Debugger listening on ws://127.0.0.1:46209/0900d6b7-c816-47b3-9086-0d5d5e79bf0b
For help, see: https://nodejs.org/en/docs/inspector
info: start fetching {"timestamp":"2019-06-20T12:44:16.901Z"}
info: fetch every 1 minutes {"timestamp":"2019-06-20T12:44:16.902Z"}
debug: fetching https://lorem-rss.herokuapp.com/feed?unit=second {"timestamp":"2019-06-20T12:44:16.917Z"}
debug: fetching https://ourbits.club/torrentrss.php?xxxxxxxxxxxxxxxxx {"timestamp":"2019-06-20T12:44:16.920Z"}
info: fetch a round {"timestamp":"2019-06-20T12:44:17.875Z"}

**Comment by fengkx** [comment]
https://github.com/fengkx/NodeRSSBot/blob/1cf9a970ed44b4739d2860802bb74408febe89a9/index.js#L240-L245

最近的更改中加入了环境变量判断fork的子进程是否监听debugger的操作。如果不设置的话就会一直等待debugger的连接。所以需要设置`NODE_PRODUTION`环境变量。现在 start script 会默认加上这个环境变量。你可以直接用 `npm start`来启动
https://github.com/fengkx/NodeRSSBot/blob/1cf9a970ed44b4739d2860802bb74408febe89a9/README.md#L171-L175

**Comment by xinxijishuwyq** [comment]
> https://github.com/fengkx/NodeRSSBot/blob/1cf9a970ed44b4739d2860802bb74408febe89a9/index.js#L240-L245
> 
> 最近的更改中加入了环境变量判断fork的子进程是否监听debugger的操作。如果不设置的话就会一直等待debugger的连接。所以需要设置`NODE_PRODUTION`环境变量。现在 start script 会默认加上这个环境变量。你可以直接用 `npm start`来启动
> https://github.com/fengkx/NodeRSSBot/blob/1cf9a970ed44b4739d2860802bb74408febe89a9/README.md#L171-L175

谢谢
