### ISSUE TITLE
一些 RSS 源内容无法抓取

### ISSUE THREAD

**Issue by gelmannt** [fengkx/NodeRSSBot#57]
简单来说就是通过 RSSHub 抓取的 twitter 内容，在 NodeRSSBot 中无法正常推送，其余的网站 RSS 源不存在这样的问题

**Comment by fengkx** [comment]
提示什么还是完全没有提示 有log吗？

**Comment by gelmannt** [comment]
> 提示什么还是完全没有提示 有log吗？

完全没有提示，就是 telegram 的 bot 上完全没有输出，我在 NodeRSSBot 已经订阅了https://rsshub.app/twitter/user/YahooNewsTopics，尽管twitter帐号内容在更新，但是 bot 完全没有内容输出

**Comment by fengkx** [comment]
我在demo中订阅上面连接能够正常收到更新。自建的话麻烦提供log

**Comment by gelmannt** [comment]
> 我在demo中订阅上面连接能够正常收到更新。自建的话麻烦提供log

2|node_rss | info: fetch every 1 minutes {"timestamp":"2019-08-09T05:49:08.103Z"}
2|node_rss | info: fetch a round {"timestamp":"2019-08-09T05:49:08.132Z"}
2|node_rss | info: start fetching {"timestamp":"2019-08-09T05:50:00.033Z"}
2|node_rss | info: fetch a round {"timestamp":"2019-08-09T05:50:00.035Z"}
2|node_rss | info: start fetching {"timestamp":"2019-08-09T05:51:00.046Z"}
2|node_rss | info: fetch a round {"timestamp":"2019-08-09T05:51:00.884Z"}
2|node_rss | error: Bad Request: can't parse entities: Expected end tag at byte offset 156 {"timestamp":"2019-08-09T05:51:01.787Z"}
2|node_rss | info: start fetching {"timestamp":"2019-08-09T05:52:00.064Z"}
2|node_rss | info: fetch a round {"timestamp":"2019-08-09T05:52:00.869Z"}
2|node_rss | info: start fetching {"timestamp":"2019-08-09T05:53:00.055Z"}
2|node_rss | info: fetch a round {"timestamp":"2019-08-09T05:53:00.824Z"}
2|node_rss | info: start fetching {"timestamp":"2019-08-09T05:54:00.027Z"}
2|node_rss | info: fetch a round {"timestamp":"2019-08-09T05:54:00.780Z"}
2|node_rss | info: start fetching {"timestamp":"2019-08-09T05:55:00.037Z"}
2|node_rss | info: fetch a round {"timestamp":"2019-08-09T05:55:00.790Z"}

2|node_rssbot  | info: start fetching {"timestamp":"2019-08-09T05:56:00.068Z"}
2|node_rssbot  | info: fetch a round {"timestamp":"2019-08-09T05:56:01.034Z"}
2|node_rssbot  | error: Bad Request: can't parse entities: Expected end tag at byte offset 152 {"timestamp":"2019-08-09T05:56:01.915Z"}
2|node_rssbot  | info: start fetching {"timestamp":"2019-08-09T05:57:00.065Z"}
2|node_rssbot  | info: fetch a round {"timestamp":"2019-08-09T05:57:00.860Z"}
2|node_rssbot  | error: Bad Request: can't parse entities: Expected end tag at byte offset 157 {"timestamp":"2019-08-09T05:57:01.065Z"}

**Comment by fengkx** [comment]
贴出来的log看不出什么问题。 logs下的 error log看一下

**Comment by gelmannt** [comment]
> 贴出来的 log 看不出什么问题。 logs 下的 error log 看一下

/root/.pm2/logs/node-rssbot-error.log 中没有错误日志

/root/.pm2/logs/index-error.log 中的内容

{ Error: Cannot find module 'telegraf'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Module.Hook._require.Module.require (/root/.nvm/versions/node/v10.3.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:27)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/NodeRSSBot/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Object.<anonymous> (/root/.nvm/versions/node/v10.3.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module 'telegraf'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Module.Hook._require.Module.require (/root/.nvm/versions/node/v10.3.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:27)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/NodeRSSBot/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)

**Comment by fengkx** [comment]
rssbot目录下 的logs中的error.log 或者用docker省事省心:joy:

**Comment by gelmannt** [comment]
> error.log

我是纯小白，希望大佬别见笑

{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 156","level":"error","timestamp":"2019-08-09T05:51:01.787Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 152","level":"error","timestamp":"2019-08-09T05:56:01.915Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 157","level":"error","timestamp":"2019-08-09T05:57:01.065Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 152","level":"error","timestamp":"2019-08-09T06:27:01.559Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 154","level":"error","timestamp":"2019-08-09T06:58:01.348Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 155","level":"error","timestamp":"2019-08-09T07:29:01.356Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 157","level":"error","timestamp":"2019-08-09T08:00:01.556Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 154","level":"error","timestamp":"2019-08-09T08:31:01.574Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 157","level":"error","timestamp":"2019-08-09T09:02:01.716Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 155","level":"error","timestamp":"2019-08-09T09:33:01.526Z"}
{"message":"Bad Request: can't parse entities: Expected end tag at byte offset 157","level":"error","timestamp":"2019-08-09T10:04:01.487Z"}

**Comment by gelmannt** [comment]
> rssbot 目录下 的 logs 中的 error.log 或者用 docker 省事省心😂

用 docker 布署也是同样的问题

**Comment by fengkx** [comment]
发现问题的原因是某些推文的标题中包含一些html中需要转移的字符。例如
```html
<a href="https://twitter.com/YahooNewsYuru/status/1160149802388037632">㊗️🎉🎁おめでと～～㊗️🎉🎁<br>乃木坂46・齋藤飛鳥、21歳の誕生日！ ファンから祝福の声が続々<...</a>
```
在textNode中出现了`<`，在RSSHub生成的RSS中没有转义。这样Telegram不能Parse Html会导致发送错误。在新的版本中 731a9d4fc5a57d07f9904d8f0174c908299f9a62 已经解决。更新代码或者docker就好了。

感谢

**Comment by gelmannt** [comment]
> 发现问题的原因是某些推文的标题中包含一些 html 中需要转移的字符。例如
> 
> ```
> <a href="https://twitter.com/YahooNewsYuru/status/1160149802388037632">㊗️🎉🎁おめでと～～㊗️🎉🎁<br>乃木坂46・齋藤飛鳥、21歳の誕生日！ ファンから祝福の声が続々<...</a>
> ```
> 
> 在 textNode 中出现了 `<`，在 RSSHub 生成的 RSS 中没有转义。这样 Telegram 不能 Parse Html 会导致发送错误。在新的版本中 [731a9d4](https://github.com/fengkx/NodeRSSBot/commit/731a9d4fc5a57d07f9904d8f0174c908299f9a62) 已经解决。更新代码或者 docker 就好了。
> 
> 感谢

谢谢大佬
