### ISSUE TITLE
希望把telegraph加进去，方便telegram应用内阅读

### ISSUE THREAD

**Issue by iLay1678** [fengkx/NodeRSSBot#64]
https://github.com/fonov/telegraph-node

**Comment by fengkx** [comment]
Telgraph 我觉得没有什么优势。Telegram应用内阅读也没有什么优势的样子。
当目前为止，我能想到的场景就是telegraph可以当作一个类似web archive的存在。
当初开发这个Bot就是想要可以调整抓取间隔不要那么频繁的刷屏。在一个长的时间间隔内同一个subscription的多条消息能合并发送。但是Telegraph Instant View不能。 所以暂时不考虑。

**Comment by iLay1678** [comment]
好吧，我主要用来追小说，应用内阅读对于小说很方便。目前在用flowerss
