### ISSUE TITLE
Keep notifying failure of parsing feeds generated by Feed43.com

### ISSUE THREAD

**Issue by chouj** [fengkx/NodeRSSBot#65]
but the bot is actually able to push new items in those feeds.

An issue due to rss-parser ?

**Comment by fengkx** [comment]
Would you mind share the feed url ?

**Comment by chouj** [comment]
For example: https://node2.feed43.com/2134534252708061.xml

**Comment by fengkx** [comment]
When I look at the banned list of ip yesterday, It seem that the demo server has been [banned by feed43](https://node2.feed43.com/banned.htm) because there are too much request to exact the Url above. for now demo fetch the feed every 15 minutes.

According to feed43
> Request any of Feed43 feeds for 96 times in a 24-hour frame (approx. 1 request per 15 minutes), and you will see your IP in 'Banned Temporarily' list.

**Comment by chouj** [comment]
Great. Thanks. This issue can be closed now.
