### ISSUE TITLE
i18n: Add and Imporve translation 

### ISSUE THREAD

**Issue by fengkx** [fengkx/NodeRSSBot#67]
## 2020 Hacktoberfest update

There are some words updated in `zh-cn.yaml`, `zh-tw.yaml` and `en.yaml` but no other languages. 

---

The bot supports switching language using `/lang` command.
 For now, It supports languages listed in [README](https://github.com/fengkx/NodeRSSBot#support-language).

We can add more translation by adding a yaml file named by a lower case [language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) in the i18n directory. For example: https://github.com/fengkx/NodeRSSBot/pull/52

**The translation should be based on [zh-cn.yaml](https://github.com/fengkx/NodeRSSBot/blob/master/i18n/zh-cn.yaml) or [en.yaml](https://github.com/fengkx/NodeRSSBot/blob/master/i18n/en.yaml)** which is maintained by repository owner(get updates with latest strings)
PR welcome.

**Comment by dubaid** [comment]
Added pt-br - https://github.com/fengkx/NodeRSSBot/pull/68

**Comment by fengkx** [comment]
`es-es.yaml` Spanish translation is missing some strings. For now it just fallback to English.

**Comment by vherasme** [comment]
> 
> 
> `es-es.yaml` Spanish translation is missing some strings. For now it just fallback to English.

Can I improve that translation? Bear in mind however that some English words are so common that they're not translated in some cases. Especially those related to technology

**Comment by wait-what** [comment]
I don't know if you need this, but I'll add Lithuanian

**Comment by fengkx** [comment]
@vherasme There are 7 strings didn't have translation in Spanish. I think it would be better to translate it for consistency please.

**Comment by dukkee** [comment]
@fengkx Added russian #76
