### ISSUE TITLE
使用pm2，运行错误

### ISSUE THREAD

**Issue by walterjobs** [fengkx/NodeRSSBot#721]
错误报告如下
│                                 ││ node_rssbot > > noderssbot@0.11.0 start /root                                 │
│                                 ││ node_rssbot > > cross-env NODE_PRODUTION=true node dist/source/index.js   
│                                 ││ node_rssbot > sh: 1: cross-env: not found                                     │
│                                 ││ node_rssbot > npm ERR! code ELIFECYCLE                                        │
│                                 ││ node_rssbot > npm ERR! syscall spawn                                          │
│                                 ││ node_rssbot > npm ERR! file sh                                                │
│                                 ││ node_rssbot > npm ERR! errno ENOENT                                           │
│                                 ││ node_rssbot > npm ERR! noderssbot@0.11.0 start: `cross-env NODE_PRODUTION=tr  │
│                                 ││ node_rssbot > npm ERR! spawn ENOENT                                           │
│                                 ││ node_rssbot > npm ERR!                                                        │
│                                 ││ node_rssbot > npm ERR! Failed at the noderssbot@0.11.0 start script.          │
│                                 ││ node_rssbot > npm ERR! This is probably not a problem with npm. There is      │
│                                 ││ node_rssbot > npm WARN Local package.json exists, but node_modules missing,   │
│                                 ││ node_rssbot > npm ERR! A complete log of this run can be found in:            │
│                                 ││ node_rssbot > npm ERR!     /root/.npm/_logs/2022-03-22T16_48_04_113Z-debug.l  │

麻烦大佬帮忙看看

**Comment by fengkx** [comment]
> │ ││ node_rssbot > sh: 1: cross-env: not found │
问题在于 cross-env 没有在PATH 里,安装依赖了吗

**Comment by walterjobs** [comment]
> 

使用npm i安装了
