### ISSUE TITLE
Feeds of .opml import with channel ID shown in bot's private chat

### ISSUE THREAD

**Issue by DrNion** [fengkx/NodeRSSBot#82]
I created multiple `.opml` files ready for import. Their filenames had my private channels IDs (with `-100` at the beginning). 

The import went flawless but when I got the first RSS-Feeds they appeared in my bot's private chat and not in my channels. 

With `/sub <channel_ID> <RSS_URL>` I don't have that problem.

**Comment by fengkx** [comment]
How to get the ID of a channel instead of username of it?

**Comment by DrNion** [comment]
I used [the channels ID](https://github.com/GabrielRF/telegram-id#web-channel-id) and no username or user ID.

You can export from channels by `/export  <channel ID>` but it's not possible with `/import <channel ID>` since the output is just a normal instruction of how to send the .opml file. 

I'd have an idea of how to `/import` multiple subs for multiple channels with just one .opml file.
Is it possible to create a `<body>`like this? 
```
<outline type="rss" text="Text Example" channel_id="-1001234567890" xmlUrl="url.example.com"/>
```

I don't know coding otherwise I'd be happy to help you :)

**Comment by fengkx** [comment]
The same issue as `/sub`. Fix now. Have a try.

**Comment by DrNion** [comment]
Now it works, thanks!
