### ISSUE TITLE
请问，如果想自行修改推送时的消息可以做到吗?

### ISSUE THREAD

**Issue by ShadowsSide** [fengkx/NodeRSSBot#882]
比如改成

 “””
#tag #tag

RRS抓取内容标题

频道:@xxxx
群组:@xxxx
“””

若能提供帮助，感激不尽！

**Comment by ShadowsSide** [comment]
我是用来推送自己博客的RSS，所以想要自定义下这个内容

**Comment by fengkx** [comment]
You need to fork and change the code yourself

**Comment by ShadowsSide** [comment]
> You need to fork and change the code yourself

Get it. I just want to know which file to modify and I will test the rest by myself

**Comment by fengkx** [comment]
https://github.com/fengkx/NodeRSSBot/blob/7a44df8d689fc66498d6032d16cf74bf84d7a12e/source/utils/send.ts#L76

**Comment by ShadowsSide** [comment]
Thanks!
